#!/usr/bin/env npx ts-node

/**
 * Generate Design Tokens Script
 * Creates TypeScript design token files from a configuration
 * 
 * Usage: npx ts-node generate_tokens.ts
 */

import * as fs from 'fs'
import * as path from 'path'

interface TokenConfig {
  colors: Record<string, Record<string, string>>
  spacing: Record<string, string>
  fontSize: Record<string, [string, { lineHeight: string }]>
  fontFamily: Record<string, string[]>
  borderRadius: Record<string, string>
  shadows: Record<string, string>
}

const defaultTokens: TokenConfig = {
  colors: {
    primary: {
      '50': '#eff6ff',
      '100': '#dbeafe',
      '200': '#bfdbfe',
      '300': '#93c5fd',
      '400': '#60a5fa',
      '500': '#3b82f6',
      '600': '#2563eb',
      '700': '#1d4ed8',
      '800': '#1e40af',
      '900': '#1e3a8a',
    },
    neutral: {
      '50': '#fafafa',
      '100': '#f4f4f5',
      '200': '#e4e4e7',
      '300': '#d4d4d8',
      '400': '#a1a1aa',
      '500': '#71717a',
      '600': '#52525b',
      '700': '#3f3f46',
      '800': '#27272a',
      '900': '#18181b',
    },
    success: {
      '50': '#f0fdf4',
      '500': '#22c55e',
      '600': '#16a34a',
      '700': '#15803d',
    },
    warning: {
      '50': '#fffbeb',
      '500': '#f59e0b',
      '600': '#d97706',
      '700': '#b45309',
    },
    error: {
      '50': '#fef2f2',
      '500': '#ef4444',
      '600': '#dc2626',
      '700': '#b91c1c',
    },
  },
  spacing: {
    '0': '0',
    '0.5': '0.125rem',
    '1': '0.25rem',
    '1.5': '0.375rem',
    '2': '0.5rem',
    '2.5': '0.625rem',
    '3': '0.75rem',
    '3.5': '0.875rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '7': '1.75rem',
    '8': '2rem',
    '9': '2.25rem',
    '10': '2.5rem',
    '11': '2.75rem',
    '12': '3rem',
    '14': '3.5rem',
    '16': '4rem',
    '20': '5rem',
    '24': '6rem',
    '28': '7rem',
    '32': '8rem',
  },
  fontSize: {
    xs: ['0.75rem', { lineHeight: '1rem' }],
    sm: ['0.875rem', { lineHeight: '1.25rem' }],
    base: ['1rem', { lineHeight: '1.5rem' }],
    lg: ['1.125rem', { lineHeight: '1.75rem' }],
    xl: ['1.25rem', { lineHeight: '1.75rem' }],
    '2xl': ['1.5rem', { lineHeight: '2rem' }],
    '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
    '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
    '5xl': ['3rem', { lineHeight: '1' }],
    '6xl': ['3.75rem', { lineHeight: '1' }],
  },
  fontFamily: {
    sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
    mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
  },
  borderRadius: {
    none: '0',
    sm: '0.125rem',
    DEFAULT: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    '2xl': '1rem',
    '3xl': '1.5rem',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    DEFAULT: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
    '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
    inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
    none: 'none',
  },
}

function generateTokensFile(tokens: TokenConfig): string {
  return `/**
 * Design Tokens
 * Auto-generated by generate_tokens.ts
 * 
 * Usage:
 * import { tokens } from './tokens'
 */

export const tokens = ${JSON.stringify(tokens, null, 2)} as const

export type ColorScale = keyof typeof tokens.colors
export type SpacingScale = keyof typeof tokens.spacing
export type FontSizeScale = keyof typeof tokens.fontSize
export type BorderRadiusScale = keyof typeof tokens.borderRadius
export type ShadowScale = keyof typeof tokens.shadows
`
}

function generateTailwindConfig(tokens: TokenConfig): string {
  return `/**
 * Tailwind Configuration
 * Auto-generated by generate_tokens.ts
 */

import type { Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: ${JSON.stringify(tokens.colors, null, 6).replace(/"/g, "'")},
      spacing: ${JSON.stringify(tokens.spacing, null, 6).replace(/"/g, "'")},
      fontSize: ${JSON.stringify(tokens.fontSize, null, 6).replace(/"/g, "'")},
      fontFamily: ${JSON.stringify(tokens.fontFamily, null, 6).replace(/"/g, "'")},
      borderRadius: ${JSON.stringify(tokens.borderRadius, null, 6).replace(/"/g, "'")},
      boxShadow: ${JSON.stringify(tokens.shadows, null, 6).replace(/"/g, "'")},
    },
  },
  plugins: [],
} satisfies Config
`
}

// Generate files
const outputDir = path.join(process.cwd(), 'src', 'styles')

try {
  fs.mkdirSync(outputDir, { recursive: true })
  
  const tokensContent = generateTokensFile(defaultTokens)
  const tailwindContent = generateTailwindConfig(defaultTokens)
  
  fs.writeFileSync(path.join(outputDir, 'tokens.ts'), tokensContent)
  console.log(`✅ Generated ${outputDir}/tokens.ts`)
  
  fs.writeFileSync(path.join(process.cwd(), 'tailwind.config.ts'), tailwindContent)
  console.log(`✅ Generated tailwind.config.ts`)
  
  console.log('')
  console.log('📝 Next steps:')
  console.log('   1. Review and customize the tokens in src/styles/tokens.ts')
  console.log('   2. Import tokens where needed: import { tokens } from "@/styles/tokens"')
} catch (error) {
  console.error('Error generating tokens:', error)
  process.exit(1)
}

export { defaultTokens, generateTokensFile, generateTailwindConfig }
